spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.254.252/test1?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
  jpa:
    generate-ddl: true